#ifndef _LANG
#define _LANG
#define MSG_SHIFT L"Shift"
#define MSG_CTRL L"Ctrl"
#define MSG_ALT L"Alt"
#define MSG_OK L"&OK"
#define MSG_CANCEL L"Ca&ncel"
#define MSG_CLOSE L"&Close"
#define MSG_ERROR L"Error"
#define MSG_INFO L"Information"
#define MSG_WARNING L"Warning"
#define MSG_QUESTION L"Question"
#define MSG_INPUTDEFTITLE "Input request"
#define MSG_H_OUTPUT "Output"
#define MSG_LUADB_TITLE L"Lua console"
#define MSG_CLEAR L"C&lear"
#define MSG_EVAL L"&Evaluate"
#define MSG_EVALLBL L"Evaluate: "
#define MSG_WINDOWTITLE L"%ls - %ls"
#define MSG_UNTITLED L"Untitled %d"
#define MSG_SB1 L"Li %d, col %d, %d%%"
#define MSG_SB2 L"Li %d, col %d to li %d, col%d, %d%%"
#define MSG_SAVECHANGES L"Do you want to save changes to %s before closing ?"
#define MSG_RELOAD_WARNING L"Are you sure to reload current file ?\r\nYou are going to lose all modifications made after its last save."
#define MSG_CROSSMODIFICATIONS L"The file %s has been modified by another process. Would you like to reload it ?\r\nYou may loose unsaved work."
#define MSG_SAVEONCRASH L"A fatal error occured and the application must immediately be closed.\r\nA backup of the currently editing file has been saved in %ls-auto-save.tmp.\r\nWe are sorry for the inconvenience."
#define MSG_GOTOLINETITLE L"Go to line"
#define MSG_GOTOLINETEXT L"Go to &line (max. %d : )"
#define MSG_GOTOLINE_RANGE_ERROR L"Line number out of range"
#define MSG_REPL_SEARCH L"&Search: "
#define MSG_REPL_REPLACE L"&Replace with: "
#define MSG_REPL_CBCASE L"&Case sensitive"
#define MSG_REPL_CBLUA L"Regular e&xpression"
#define MSG_REPL_CBUTF8 L"&Unicode extensions"
#define MSG_REPL_DIRECTION L"Search direction: "
#define MSG_REPL_DIRECTION_UP L"&Up"
#define MSG_REPL_DIRECTION_DOWN L"&Down"
#define MSG_REPL_DLGTITLE1 L"Find"
#define MSG_REPL_DLGTITLE2 L"Search and replace"
#define MSG_REPL_BTNOK1 L"&Find"
#define MSG_REPL_BTNOK2 L"Replace &all"
#define MSG_REPL_REGEXERROR L"Syntax error in the regular expression"
#define MSG_REPL_REPLSUCCESS L"%d replacements done"
#define MSG_OPENTITLE L"Open"
#define MSG_SAVETITLE L"SAve as"
#define MSG_FILENAMEFILTER L"All files\0*.*\0"
#define MSG_READ_ERROR L"Unable to open the file"
#define MSG_WRITE_ERROR L"Unable to save the file"

#define MSG_FILEMENU L"&File"
#define MSG_EDITMENU L"&Edit"
#define MSG_FORMATMENU L"F&ormat"
#define MSG_LINEENDINGMENU L"&Line ending"
#define MSG_ENCODINGMENU "&Encoding"
#define MSG_INDENTMENU L"Indentation &mode"
#define MSG_INDENT_TAB L"&Tabs"
#define MSG_INDENT_SPACES L"%d &spaces"
#define MSG_INDENT_SPACES_DEF L"&Spaces"
#define MSG_LINEWRAP L"Auto line &wrap"
#define MSG_AUTORELOAD L"Auto &reload"
#define MSG_NEW L"&New\aCtrl+N"
#define MSG_OPEN L"&Open...\aCtrl+O"
#define MSG_OPEN_NEW_INSTANCE L"Open in a new &instance...\aCtrl+Shift+O"
#define MSG_OPEN_FORCE L"Open &using selected encoding..."
#define MSG_SAVE L"&Save\aCtrl+S"
#define MSG_SAVE_AS L"Sa&ve as...\aCtrl+Shift+S"
#define MSG_RECENT_FILES L"Recent &files"
#define MSG_EXIT L"E&xit\aAlt+F4"
#define MSG_CLOSE2 L"&Close\aCtrl+F4"
#define MSG_UNDO L"&Undo\aCtrl+Z"
#define MSG_REDO L"Re&do\aCtrl+Shift+Z"
#define MSG_COPY L"&Copy\aCtrl+C"
#define MSG_CUT L"Cu&t\aCtrl+X"
#define MSG_PASTE L"&Paste\aCtrl+V"
#define MSG_SELECTALL L"Select &all\aCtrl+A"
#define MSG_GOTOLINE L"&Go to line...\aCtrl+G"
#define MSG_FIND L"&Find...\aCtrl+F"
#define MSG_REPLACE L"Search and &replace...\aCtrl+H"
#define MSG_FINDNEXT L"Find &next\aF3"
#define MSG_FINDPREV L"Find pre&vious\aShift+F3"
#define MSG_SWITCHCURSOR L"S&witch cursor\aF4"
#define MSG_JOINCURSOR L"Join cursors\aShift+F4"
#define MSG_CURSORSELECT L"Select to second curs&or\aCtrl+Shift+A"
#define MSG_LE_DOS L"&DOS/Windows (CRLF)"
#define MSG_LE_UNIX L"&Unix/linux (LF)"
#define MSG_LE_MAC L"&Macintosh (CR)"
#define MSG_ENC0 L"Windows/&ANSI"
#define MSG_ENC1 L"UTF-&7"
#define MSG_ENC2 L"UTF-&8"
#define MSG_ENC3 L"UTF-8 with &BOM"
#define MSG_ENC4 L"&Unicode"
#define MSG_ENC5 L"Unicode with B&OM"
#define MSG_ENC6 L"Unicode bi&g-endian"
#define MSG_ENC7 L"Unicode big-endian wit&h BOM"
#define MSG_ENC8 L"ISO-8859-1&5/Latin-9"
#define MSG_ENC9 L"IBM &437 / International DOS"
#define MSG_ENC10 L"IBM 850 / Latin-1 &DOS"
#define MSG_ENC11 L"IBM &EBCDIC"
#define MSG_ENC12 L"&Macintosh latin-1"
#define MSG_RELOAD L"Re&load"
#define MSG_RELOAD_FORCEENCODING L"Reload using selected &encoding\aCtrl+F5"
#define MSG_SMARTHOME L"Smart &home key"
#define MSG_KEEPINDENT L"Follow &indent"
#define MSG_SHOWSTATUS L"Show status &bar"
#define MSG_TOOLS_MENU L"&Tools"
#define MSG_CONSOLE L"Lua &console"
#define MSG_HELPMENU L"&Help"
#define MSG_ABOUT L"About 6Pad..."
#define MSG_ABOUTTITLE L"About 6Pad"
#define MSG_ABOUTMSG L"6Pad\r\n\tVersion " VERSION_STRING L"\r\n\tCopyright \xA9 2010, QuentinC http://quentinc.net/"
#endif
